worker_processes 1;

error_log /tmp/santinhohunter-nginx-error.log warn;
pid /tmp/santinhohunter-nginx.pid;

events {
  worker_connections 256;
}

http {
  default_type application/octet-stream;

  types {
    text/html html;
    text/css css;
    application/javascript js;
    application/json json;
    image/png png;
    image/jpeg jpg jpeg;
    image/svg+xml svg;
    font/ttf ttf;
    font/woff woff;
    font/woff2 woff2;
  }

  access_log /tmp/santinhohunter-nginx-access.log;
  sendfile on;

  server {
    listen 0.0.0.0:8088;
    server_name _;

    root "/home/markun/devel/experiments/santinhohunter/dist";
    index index.html;

    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
